[env:tsim7000g]
platform = espressif32
board = esp32dev
framework = arduino

board_build.filesystem = littlefs

upload_speed  = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_flags = 
    -DCORE_DEBUG_LEVEL=0
    -O2

lib_deps =
    https://github.com/me-no-dev/AsyncTCP.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/jgromes/RadioLib.git
    vshymanskyy/TinyGSM @ ^0.12.0
    bblanchon/ArduinoJson @ ^7.0.4
    kosme/arduinoFFT @ ^1.6.0

build_type = release